default: &default
  adapter: <%= databaseAdapter %>
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: <%= ENV.fetch("DATABASE_HOST") { "postgres" } %>
  port: <%= ENV.fetch("DATABASE_PORT") { "5432" } %>
  username: <%= ENV.fetch("DATABASE_USERNAME") { "postgres" } %>
  password: <%= ENV.fetch("DATABASE_PASSWORD") { "password" } %>

development:
  <<: *default
  database: <%= appName %>_development

test:
  <<: *default
  database: <%= appName %>_test

production:
  <<: *default
  database: <%= appName %>_production
  url: <%= ENV['DATABASE_URL'] %>
