source "https://rubygems.org"
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby "<%= rubyVersion %>"

# Rails core
gem "rails", "~> <%= railsVersion %>"
gem "puma", "~> 6.0"

# Database
gem "pg", "~> 1.1"
gem "sqlite3", "~> 1.4", platforms: %i[ mingw mswin x64_mingw jruby ]

# API and JSON
gem "jbuilder", "~> 2.7"
gem "rack-cors"

# Environment variables
gem "dotenv-rails", "~> 2.8"

# GraphQL
gem "graphql", "~> 2.0"
gem "graphiql-rails", group: :development

# Authentication
<%= AUTHENTICATION_GEMS %>

# API Documentation
<%= API_DOCS_GEMS %>

# Development and Test
group :development, :test do
  gem "debug", platforms: %i[ mri mingw x64_mingw ]
  gem "rspec-rails", "~> 6.0"
  gem "factory_bot_rails"
  gem "faker"
  gem "shoulda-matchers"
  gem "database_cleaner-active_record"
end

group :development do
  gem "web-console"
  gem "rack-mini-profiler"
  gem "listen", "~> 3.3"
  gem "spring"

  # Code quality
  <%= LINTING_GEMS %>

  # Type checking
  <%= TYPE_CHECKING_GEMS %>
end

group :test do
  gem "capybara"
  gem "selenium-webdriver"
  gem "webdrivers"
end

# Windows does not include zoneinfo files, so bundle the tzinfo-data gem
gem "tzinfo-data", platforms: %i[ mingw mswin x64_mingw jruby ]

# Reduces boot times through caching; required in config/boot.rb
gem "bootsnap", require: false
